In [1]:
import numpy as np
import random

In [2]:
l1_wvector = np.array([[0.5,1.5,0.8],
                       [0.8,0.2,-1.6],
                                   ])
l2_wvector = np.array([[0.9,-1.7,1.6],
                       [1.2,2.1,-0.2],
                                   ])

feature_vector = np.array([1,0.7,1.2])
true_value = np.array([1,0])
learning_rate = 0.05

In [5]:
import numpy as np

def sum_of_products(array1, array2):
    # Ensure both arrays have the same shape
    if array1.shape != array2.shape:
        raise ValueError("Arrays must have the same shape")

    # Calculate the sum of products of respective terms
    result = np.sum(array1 * array2)

    return result

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sum_of_squared_differences(array1, array2):
    # Ensure both arrays have the same shape
    if array1.shape != array2.shape:
        raise ValueError("Arrays must have the same shape")

    # Calculate the squared differences and sum them
    squared_differences = (array1 - array2) ** 2
    result = (np.sum(squared_differences))/2

    return result

def compute_expression(a, b):
    result = (a - b) * a * (1 - a)
    return result

def compute_expression_1(a, b):
    result =  a * (1 - b) * b
    return result

def update_weight_vector(a, b, c):
    result = a - b * c
    return result

def elements_to_array(element1, element2):
    return np.array([element1, element2])

# Example usage
# Define your variables and arrays here
# For example:
# l1_wvector = np.array([[1, 2, 3], [4, 5, 6]])
# feature_vector = np.array([0.1, 0.2, 0.3])
# true_value = np.array([0.7, 0.8])
# learning_rate = 0.01

# node_layer_kth_node
node_1_1 = sigmoid(sum_of_products(l1_wvector[0], feature_vector))
node_1_2 = sigmoid(sum_of_products(l1_wvector[1], feature_vector))
feature_vector_2 = np.array([1, node_1_1, node_1_2])
node_2_1 = sigmoid(sum_of_products(l2_wvector[0], feature_vector_2))
node_2_2 = sigmoid(sum_of_products(l2_wvector[1], feature_vector_2))
output_value = np.array([node_2_1, node_2_2])
error = sum_of_squared_differences(output_value, true_value)

# Calculate derivatives
der_w2_01 = compute_expression(node_2_1, true_value[0]) * 1
der_w2_11 = compute_expression(node_2_1, true_value[0]) * node_1_1
der_w2_21 = compute_expression(node_2_1, true_value[0]) * node_1_2
der_w2_02 = compute_expression(node_2_2, true_value[1]) * 1
der_w2_12 = compute_expression(node_2_2, true_value[1]) * node_1_1
der_w2_22 = compute_expression(node_2_2, true_value[1]) * node_1_2

# Perform computations with arrays
array_1 = elements_to_array(compute_expression(node_2_1, true_value[0]), compute_expression(node_2_2, true_value[1]))
array_2 = elements_to_array(l2_wvector[0][1], l2_wvector[1][1])
array_3 = elements_to_array(l2_wvector[0][2], l2_wvector[1][2])
value_1 = compute_expression_1(sum_of_products(array_1, array_2), node_1_1)
value_2 = compute_expression_1(sum_of_products(array_1, array_3), node_1_2)
der_w1_01 = value_1 * feature_vector[0]
der_w1_11 = value_1 * feature_vector[1]
der_w1_21 = value_1 * feature_vector[2]
der_w1_02 = value_2 * feature_vector[0]
der_w1_12 = value_2 * feature_vector[1]
der_w1_22 = value_2 * feature_vector[2]

print(f"Error: {error}\n")
print(f"{der_w2_01}\t{der_w2_11}\t{der_w2_21}\n{der_w2_02}\t{der_w2_12}\t{der_w2_22}\n")
print(f"{der_w1_01}\t{der_w1_11}\t{der_w1_21}\n{der_w1_02}\t{der_w1_12}\t{der_w1_22}\n")
# Update weights
l2_wvector[0][0] = update_weight_vector(l2_wvector[0][0], learning_rate, der_w2_01)
l2_wvector[0][1] = update_weight_vector(l2_wvector[0][1], learning_rate, der_w2_11)
l2_wvector[0][2] = update_weight_vector(l2_wvector[0][2], learning_rate, der_w2_21)
l2_wvector[1][0] = update_weight_vector(l2_wvector[1][0], learning_rate, der_w2_02)
l2_wvector[1][1] = update_weight_vector(l2_wvector[1][1], learning_rate, der_w2_12)
l2_wvector[1][2] = update_weight_vector(l2_wvector[1][2], learning_rate, der_w2_22)

print(f'{l2_wvector}')

l1_wvector[0][0] = update_weight_vector(l1_wvector[0][0], learning_rate, der_w1_01)
l1_wvector[0][1] = update_weight_vector(l1_wvector[0][1], learning_rate, der_w1_11)
l1_wvector[0][2] = update_weight_vector(l1_wvector[0][2], learning_rate, der_w1_21)
l1_wvector[1][0] = update_weight_vector(l1_wvector[1][0], learning_rate, der_w1_02)
l1_wvector[1][1] = update_weight_vector(l1_wvector[1][1], learning_rate, der_w1_12)
l1_wvector[1][2] = update_weight_vector(l1_wvector[1][2], learning_rate, der_w1_22)

print(f'{l1_wvector}')


Error: 0.613362534613651

-0.13773709407665294	-0.12738475900610174	-0.03758732127856747
0.039899464922185435	0.03690061677035571	0.01088823614964972

0.02210048336900762	0.015470338358305333	0.026520580042809144
-0.045311465404214844	-0.03171802578295039	-0.054373758485057815

[[ 0.90688685 -1.69363076  1.60187937]
 [ 1.19800503  2.09815497 -0.20054441]]
[[ 0.49889498  1.49922648  0.79867397]
 [ 0.80226557  0.2015859  -1.59728131]]


In [7]:
n_iterations = 100  # Define the number of iterations
for i in range(n_iterations):
    # Forward propagation
    node_1_1 = sigmoid(sum_of_products(l1_wvector[0], feature_vector))
    node_1_2 = sigmoid(sum_of_products(l1_wvector[1], feature_vector))
    feature_vector_2 = np.array([1, node_1_1, node_1_2])
    node_2_1 = sigmoid(sum_of_products(l2_wvector[0], feature_vector_2))
    node_2_2 = sigmoid(sum_of_products(l2_wvector[1], feature_vector_2))
    output_value = np.array([node_2_1, node_2_2])
    
    # Backpropagation
    error = sum_of_squared_differences(output_value, true_value)
    der_w2_01 = compute_expression(node_2_1, true_value[0]) * 1
    der_w2_11 = compute_expression(node_2_1, true_value[0]) * node_1_1
    der_w2_21 = compute_expression(node_2_1, true_value[0]) * node_1_2
    der_w2_02 = compute_expression(node_2_2, true_value[1]) * 1
    der_w2_12 = compute_expression(node_2_2, true_value[1]) * node_1_1
    der_w2_22 = compute_expression(node_2_2, true_value[1]) * node_1_2
    
    array_1 = elements_to_array(compute_expression(node_2_1, true_value[0]), compute_expression(node_2_2, true_value[1]))
    array_2 = elements_to_array(l2_wvector[0][1], l2_wvector[1][1])
    array_3 = elements_to_array(l2_wvector[0][2], l2_wvector[1][2])
    value_1 = compute_expression_1(sum_of_products(array_1, array_2), node_1_1)
    value_2 = compute_expression_1(sum_of_products(array_1, array_3), node_1_2)
    der_w1_01 = value_1 * feature_vector[0]
    der_w1_11 = value_1 * feature_vector[1]
    der_w1_21 = value_1 * feature_vector[2]
    der_w1_02 = value_2 * feature_vector[0]
    der_w1_12 = value_2 * feature_vector[1]
    der_w1_22 = value_2 * feature_vector[2]
    
    # Update weights
    l2_wvector[0][0] = update_weight_vector(l2_wvector[0][0], learning_rate, der_w2_01)
    l2_wvector[0][1] = update_weight_vector(l2_wvector[0][1], learning_rate, der_w2_11)
    l2_wvector[0][2] = update_weight_vector(l2_wvector[0][2], learning_rate, der_w2_21)
    l2_wvector[1][0] = update_weight_vector(l2_wvector[1][0], learning_rate, der_w2_02)
    l2_wvector[1][1] = update_weight_vector(l2_wvector[1][1], learning_rate, der_w2_12)
    l2_wvector[1][2] = update_weight_vector(l2_wvector[1][2], learning_rate, der_w2_22)

    l1_wvector[0][0] = update_weight_vector(l1_wvector[0][0], learning_rate, der_w1_01)
    l1_wvector[0][1] = update_weight_vector(l1_wvector[0][1], learning_rate, der_w1_11)
    l1_wvector[0][2] = update_weight_vector(l1_wvector[0][2], learning_rate, der_w1_21)
    l1_wvector[1][0] = update_weight_vector(l1_wvector[1][0], learning_rate, der_w1_02)
    l1_wvector[1][1] = update_weight_vector(l1_wvector[1][1], learning_rate, der_w1_12)
    l1_wvector[1][2] = update_weight_vector(l1_wvector[1][2], learning_rate, der_w1_22)

    print(f"Iteration {i+1}: Error = {error}")
    print(f"Updated l1_wvector: {l1_wvector}")
    print(f"Updated l2_wvector: {l2_wvector}")
    print(f"\n")
print("Final l1_wvector:")
print(l1_wvector)
print("Final l2_wvector:")
print(l2_wvector)




Iteration 1: Error = 0.46832106890424985
Updated l1_wvector: [[ 0.40495731  1.43347012  0.68594877]
 [ 0.99043021  0.33330115 -1.37148375]]
Updated l2_wvector: [[ 1.38083953 -1.25977947  1.75763106]
 [ 0.94345595  1.86576225 -0.28774639]]


Iteration 2: Error = 0.46743837253604803
Updated l1_wvector: [[ 0.40412082  1.43288457  0.68494498]
 [ 0.9918444   0.33429108 -1.36978672]]
Updated l2_wvector: [[ 1.38367894 -1.25721535  1.75875555]
 [ 0.94025248  1.86286937 -0.28901506]]


Iteration 3: Error = 0.4665578519930537
Updated l1_wvector: [[ 0.40328403  1.43229882  0.68394083]
 [ 0.99325224  0.33527657 -1.36809731]]
Updated l2_wvector: [[ 1.3864934  -1.25467437  1.75987295]
 [ 0.93703158  1.85996144 -0.29029382]]


Iteration 4: Error = 0.4656793022172273
Updated l1_wvector: [[ 0.40244688  1.43171281  0.68293625]
 [ 0.99465385  0.33625769 -1.36641538]]
Updated l2_wvector: [[ 1.3892832  -1.25215625  1.76098331]
 [ 0.9337931   1.85703834 -0.29158276]]


Iteration 5: Error = 0.464802519830497